with open('schema_engine.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# The function insert_metadata starts at line 83 (index 82 in lines array)
new_lines = lines[:81] + [
'def insert_metadata(conn, config, schema):\n',
'\n',
'    cur = conn.cursor()\n',
'\n',
'    cur.execute("""\n',
'    DELETE FROM dyn_etl.metadata\n',
'    WHERE SOURCE_TABLE_NAME = %s\n',
'    """, (config.get("source_table_name"),))\n',
'\n',
'    for i, col in enumerate(schema, start=1):\n',
'\n',
'        if isinstance(col, dict):\n',
'            column_name = col.get("column_name")\n',
'            data_type = col.get("data_type", "TEXT")\n',
'            change_event = col.get("change_event", "ADD")\n',
'            change_type = col.get("change_type", "NEW_COLUMN")\n',
'            old_target_value = col.get("old_target_value")\n',
'        elif isinstance(col, str):\n',
'            column_name = col\n',
'            data_type = "TEXT"\n',
'            change_event = "ADD"\n',
'            change_type = "NEW_COLUMN"\n',
'            old_target_value = None\n',
'        else:\n',
'            print("⚠️ Skipping invalid column:", col)\n',
'            continue\n',
'\n',
'        dtype_lower = data_type.lower()\n',
'        if "int" in dtype_lower:\n',
'            target_data_type = "INT"\n',
'        elif "float" in dtype_lower:\n',
'            target_data_type = "DOUBLE"\n',
'        elif "datetime" in dtype_lower:\n',
'            target_data_type = "DATETIME"\n',
'        else:\n',
'            target_data_type = "VARCHAR(255)"\n',
'\n',
'        target_system_name = config.get("target_system", "UNKNOWN")\n',
'        target_database = config.get("target_database")\n',
'        target_schema = config.get("target_schema")\n',
'        target_table_name = config.get("target_table_name")\n',
'\n',
'        cur.execute("""\n',
'            INSERT INTO dyn_etl.metadata (\n',
'                SOURCE_SYSTEM,\n',
'                SOURCE_TABLE_NAME,\n',
'                SOURCE_ORDINAL_POSITION,\n',
'                SOURCE_COLUMN_NAME,\n',
'                SOURCE_DATA_TYPE,\n',
'                SOURCE_DATABASE,\n',
'                SOURCE_SCHEMA,\n',
'                TARGET_SYSTEM_NAME,\n',
'                TARGET_DATABASE,\n',
'                TARGET_SCHEMA,\n',
'                TARGET_TABLE_NAME,\n',
'                TARGET_ORDINAL_POSITION,\n',
'                TARGET_COLUMN_NAME,\n',
'                TARGET_DATA_TYPE,\n',
'                CHANGE_EVENT,\n',
'                CHANGE_TYPE,\n',
'                OLD_TARGET_VALUE,\n',
'                UPDATE_FLAG,\n',
'                EL_CREATED_DATE_TIME\n',
'            )\n',
'            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,NOW())\n',
'        """, (\n',
'            config.get("source_system"),\n',
'            config.get("source_table_name"),\n',
'            i,\n',
'            column_name,\n',
'            data_type,\n',
'            config.get("source_database"),\n',
'            config.get("source_schema"),\n',
'            target_system_name,\n',
'            target_database,\n',
'            target_schema,\n',
'            target_table_name,\n',
'            i,\n',
'            column_name,\n',
'            target_data_type,\n',
'            change_event,\n',
'            change_type,\n',
'            old_target_value,\n',
'            "Y"\n',
'        ))\n',
'\n',
'    conn.commit()\n'
]

with open('schema_engine.py', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)
